// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYCFZHmnDbhNKQn7c5WqDGrYhOZ6rzybE',
    appId: '1:638092100248:web:b32652cd0cb8a20a0906ed',
    messagingSenderId: '638092100248',
    projectId: 'souq-corner-d1dcd',
    authDomain: 'souq-corner-d1dcd.firebaseapp.com',
    storageBucket: 'souq-corner-d1dcd.firebasestorage.app',
    measurementId: 'G-MMLPBM2B5P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdd67PwbjGatki861__hqpIYdC94-c0jM',
    appId: '1:638092100248:android:2f878feccb9e6fd60906ed',
    messagingSenderId: '638092100248',
    projectId: 'souq-corner-d1dcd',
    storageBucket: 'souq-corner-d1dcd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2B7JPwMM4md4gX8i8Packn3KCyw8-MwE',
    appId: '1:638092100248:ios:48ce70097db683a30906ed',
    messagingSenderId: '638092100248',
    projectId: 'souq-corner-d1dcd',
    storageBucket: 'souq-corner-d1dcd.firebasestorage.app',
    iosBundleId: 'com.example.souqCorner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2B7JPwMM4md4gX8i8Packn3KCyw8-MwE',
    appId: '1:638092100248:ios:48ce70097db683a30906ed',
    messagingSenderId: '638092100248',
    projectId: 'souq-corner-d1dcd',
    storageBucket: 'souq-corner-d1dcd.firebasestorage.app',
    iosBundleId: 'com.example.souqCorner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYCFZHmnDbhNKQn7c5WqDGrYhOZ6rzybE',
    appId: '1:638092100248:web:98cfbeac1358eae20906ed',
    messagingSenderId: '638092100248',
    projectId: 'souq-corner-d1dcd',
    authDomain: 'souq-corner-d1dcd.firebaseapp.com',
    storageBucket: 'souq-corner-d1dcd.firebasestorage.app',
    measurementId: 'G-LVYWHFT2LC',
  );
}
